### ISSUE TITLE
Поведение компонентов с настройками readonly и disabled.

### ISSUE THREAD

**Issue by AlekseySorokin** [universal-editor/universal-editor#106]
В случае отсутствия значения поля на странице отображается один заголовок компонента. 
Выглядит странно. Нужно вообще ничего не выводить.

**Comment by niksamokhvalov** [comment]
Нужно не показывать поле, если компонент вызван в режиме создания новой записи. Показывать только в режиме просмотра или редактирования.

Так же нужно учесть, что внутри ue-tab может быть несколько компонентов, и все они будут readonly. В этом случае там в режиме создания новой записи так же не нужно показывать, ибо он внутри будет пустым.

На параметр disabled эта логика не распространяется.

**Comment by AlekseySorokin** [comment]
1. readonly и disabled — никогда не отправляем значения на сервер.
2. readonly — показываем заблокированный контролл.
3. disabled — показываем только значение.
4. Если данных с сервера нет, то disabled-поле не показываем. На readonly-поле данное правило не распространяется.
