### ISSUE TITLE
Ue-dropdown and ue-autocomplete components with the same reference on configuration

### ISSUE THREAD

**Issue by AlekseySorokin** [universal-editor/universal-editor#125]
Требуется организовать связность ue-dropdown (и ue-autocomplete) компонентов, чтобы при выборе значения у одного, это значение пропадало  из возможного списка значений для выбора у других компонентов. Такое поведение компонентов предполагается, если использовать одну и ту же ссылку на объект с конфигурацией.

**Comment by niksamokhvalov** [comment]
Реализовано в #130.
