### ISSUE TITLE
не срабатывает событие ue-form:componentValueChanged

### ISSUE THREAD

**Issue by NobodyDies** [universal-editor/universal-editor#195]
что то мне подсказывает что событие переименовалось в ue:componentValueChanged и оно уже отрабатывает нормально. Слушаю событие в теле контроллера с прокинутым $scope.

``` javaScript
$scope.$on('ue-form:componentValueChanged', function (event) {
      console.log(event, arguments);
    })
```

**Comment by niksamokhvalov** [comment]
Надо поправить название в доке и описать, какие данные передаются вместе с событием.

**Comment by AlekseySorokin** [comment]
#223
